"""add is_demo flags

Revision ID: 4a2a875fb9dc
Revises: c633bb4d64f4
Create Date: 2026-09-28 04:14:54.586429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a2a875fb9dc'
down_revision: Union[str, Sequence[str], None] = 'c633bb4d64f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_demo', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('workflows', sa.Column('is_demo', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflows', 'is_demo')
    op.drop_column('users', 'is_demo')
    # ### end Alembic commands ###
