"""add ticket tags

Revision ID: c633bb4d64f4
Revises: 7d4a1330581a
Create Date: 2026-09-28 02:56:21.577578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c633bb4d64f4'
down_revision: Union[str, Sequence[str], None] = '7d4a1330581a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('tags', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'tags')
    # ### end Alembic commands ###
